# Fixes errors generated by CDT in the patch files

F=$1

sed -i 's/static typeof __attribute__((__section__(".bss.percpu.read_mostly"))) //g' $F
sed -i 's/__attribute__((__section__(".bss.percpu"))) typeof//g' $F
sed -i 's/static typeof __attribute__((__section__(".bss.percpu"))) //g' $F
sed -i 's/".init.setup"/DUMMY/g' $F
sed -i "s/static const struct __attribute__((__used__))__attribute__((__section__(DUMMY)))__attribute__((__aligned__(sizeof(void\*))))//g" $F
sed -i 's/for (for_each_vcpu( d, v );;)/for_each_vcpu( d, v )/g' $F
sed -i 's/for (for_each_vcpu ( d, v );;){/for_each_vcpu ( d, v ){/g' $F
sed -i 's/for (list_for_each(pos, launched_list);;){/list_for_each(pos, launched_list){/g' $F
sed -i 's/for (list_for_each_entry_safe(vmx, tmp, blocked_vcpus, pi_blocking.list);;){/list_for_each_entry_safe(vmx, tmp, blocked_vcpus, pi_blocking.list){/g' $F
sed -i 's/unsigned long DECLARE_BITMAP/DECLARE_BITMAP/g' $F
sed -i 's/for (for_each_domain ( d );;){/for_each_domain ( d ){/g' $F


sed -E -i '/case/b; s/([^ ])\.\.\.([^ ])/\1\.\2/g' $F
sed -E -i '/case/b; s/([^ ])\.\.([^ ])/\1\.\2/g' $F
sed -i 's/\.\.;/;/g' $F
sed -i 's/\.;/;/g' $F   


sed -i 's/asm("rdmsr" : "=a" vmx_msr_low , "=d" vmx_msr_high : "c" msr);/asm("rdmsr" : "=a" (vmx_msr_low) , "=d" (vmx_msr_high) : "c" (msr));/g' $F 
sed -i 's/asm("rdmsr" : "=a" vmx_basic_msr_low , "=d" vmx_basic_msr_high : "c" 0x480);/asm("rdmsr" : "=a" (vmx_basic_msr_low) , "=d" (vmx_basic_msr_high) : "c" (0x480));/g' $F 
sed -i 's/asm("rdmsr" : "=a" must_be_one , "=d" must_be_zero : "c" msr);/asm("rdmsr" : "=a" (must_be_one) , "=d" (must_be_zero) : "c" (msr));/g' $F
sed -i 's/asm("rdmsr" : "=a" eax , "=d" edx : "c" 0x0000003a);/asm("rdmsr" : "=a" (eax) , "=d" (edx) : "c" (0x0000003a));/g' $F
sed -i 's/asm("wrmsr" : : "c" 0x0000003a , "a" eax , "d" 0);/asm("wrmsr" : : "c" (0x0000003a) , "a" (eax) , "d" (0));/g' $F

